name: aqar
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.2
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  iconsax_flutter: ^1.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  lottie: ^3.3.1
  percent_indicator: ^4.2.5
  readmore: ^3.0.0
  rename: ^3.1.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
